/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadenceRouteImport } from './routes/cadence'
import { Route as CircleRouteImport } from './routes/circle'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as DuelRouteImport } from './routes/duel'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as IntervalRouteImport } from './routes/interval'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as RealtimeRouteImport } from './routes/realtime'
import { Route as RhythmRouteImport } from './routes/rhythm'
import { Route as ScaleRouteImport } from './routes/scale'
import { Route as SensoryRouteImport } from './routes/sensory'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TriadRouteImport } from './routes/triad'
import { Route as LessonLevelRouteImport } from './routes/lesson.$level'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadenceRoute = CadenceRouteImport.update({
  id: '/cadence',
  path: '/cadence',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleRoute = CircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelRoute = DuelRouteImport.update({
  id: '/duel',
  path: '/duel',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const IntervalRoute = IntervalRouteImport.update({
  id: '/interval',
  path: '/interval',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const RealtimeRoute = RealtimeRouteImport.update({
  id: '/realtime',
  path: '/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const RhythmRoute = RhythmRouteImport.update({
  id: '/rhythm',
  path: '/rhythm',
  getParentRoute: () => rootRouteImport,
} as any)
const ScaleRoute = ScaleRouteImport.update({
  id: '/scale',
  path: '/scale',
  getParentRoute: () => rootRouteImport,
} as any)
const SensoryRoute = SensoryRouteImport.update({
  id: '/sensory',
  path: '/sensory',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TriadRoute = TriadRouteImport.update({
  id: '/triad',
  path: '/triad',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLevelRoute = LessonLevelRouteImport.update({
  id: '/lesson/$level',
  path: '/lesson/$level',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadence': typeof CadenceRoute
  '/circle': typeof CircleRoute
  '/curriculum': typeof CurriculumRoute
  '/duel': typeof DuelRoute
  '/heatmap': typeof HeatmapRoute
  '/interval': typeof IntervalRoute
  '/onboarding': typeof OnboardingRoute
  '/practice': typeof PracticeRoute
  '/realtime': typeof RealtimeRoute
  '/rhythm': typeof RhythmRoute
  '/scale': typeof ScaleRoute
  '/sensory': typeof SensoryRoute
  '/settings': typeof SettingsRoute
  '/triad': typeof TriadRoute
  '/lesson/$level': typeof LessonLevelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadence': typeof CadenceRoute
  '/circle': typeof CircleRoute
  '/curriculum': typeof CurriculumRoute
  '/duel': typeof DuelRoute
  '/heatmap': typeof HeatmapRoute
  '/interval': typeof IntervalRoute
  '/onboarding': typeof OnboardingRoute
  '/practice': typeof PracticeRoute
  '/realtime': typeof RealtimeRoute
  '/rhythm': typeof RhythmRoute
  '/scale': typeof ScaleRoute
  '/sensory': typeof SensoryRoute
  '/settings': typeof SettingsRoute
  '/triad': typeof TriadRoute
  '/lesson/$level': typeof LessonLevelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadence': typeof CadenceRoute
  '/circle': typeof CircleRoute
  '/curriculum': typeof CurriculumRoute
  '/duel': typeof DuelRoute
  '/heatmap': typeof HeatmapRoute
  '/interval': typeof IntervalRoute
  '/onboarding': typeof OnboardingRoute
  '/practice': typeof PracticeRoute
  '/realtime': typeof RealtimeRoute
  '/rhythm': typeof RhythmRoute
  '/scale': typeof ScaleRoute
  '/sensory': typeof SensoryRoute
  '/settings': typeof SettingsRoute
  '/triad': typeof TriadRoute
  '/lesson/$level': typeof LessonLevelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadence'
    | '/circle'
    | '/curriculum'
    | '/duel'
    | '/heatmap'
    | '/interval'
    | '/onboarding'
    | '/practice'
    | '/realtime'
    | '/rhythm'
    | '/scale'
    | '/sensory'
    | '/settings'
    | '/triad'
    | '/lesson/$level'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadence'
    | '/circle'
    | '/curriculum'
    | '/duel'
    | '/heatmap'
    | '/interval'
    | '/onboarding'
    | '/practice'
    | '/realtime'
    | '/rhythm'
    | '/scale'
    | '/sensory'
    | '/settings'
    | '/triad'
    | '/lesson/$level'
  id:
    | '__root__'
    | '/'
    | '/cadence'
    | '/circle'
    | '/curriculum'
    | '/duel'
    | '/heatmap'
    | '/interval'
    | '/onboarding'
    | '/practice'
    | '/realtime'
    | '/rhythm'
    | '/scale'
    | '/sensory'
    | '/settings'
    | '/triad'
    | '/lesson/$level'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadenceRoute: typeof CadenceRoute
  CircleRoute: typeof CircleRoute
  CurriculumRoute: typeof CurriculumRoute
  DuelRoute: typeof DuelRoute
  HeatmapRoute: typeof HeatmapRoute
  IntervalRoute: typeof IntervalRoute
  OnboardingRoute: typeof OnboardingRoute
  PracticeRoute: typeof PracticeRoute
  RealtimeRoute: typeof RealtimeRoute
  RhythmRoute: typeof RhythmRoute
  ScaleRoute: typeof ScaleRoute
  SensoryRoute: typeof SensoryRoute
  SettingsRoute: typeof SettingsRoute
  TriadRoute: typeof TriadRoute
  LessonLevelRoute: typeof LessonLevelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadence': {
      id: '/cadence'
      path: '/cadence'
      fullPath: '/cadence'
      preLoaderRoute: typeof CadenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle': {
      id: '/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof CircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel': {
      id: '/duel'
      path: '/duel'
      fullPath: '/duel'
      preLoaderRoute: typeof DuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interval': {
      id: '/interval'
      path: '/interval'
      fullPath: '/interval'
      preLoaderRoute: typeof IntervalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realtime': {
      id: '/realtime'
      path: '/realtime'
      fullPath: '/realtime'
      preLoaderRoute: typeof RealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rhythm': {
      id: '/rhythm'
      path: '/rhythm'
      fullPath: '/rhythm'
      preLoaderRoute: typeof RhythmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scale': {
      id: '/scale'
      path: '/scale'
      fullPath: '/scale'
      preLoaderRoute: typeof ScaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensory': {
      id: '/sensory'
      path: '/sensory'
      fullPath: '/sensory'
      preLoaderRoute: typeof SensoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triad': {
      id: '/triad'
      path: '/triad'
      fullPath: '/triad'
      preLoaderRoute: typeof TriadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$level': {
      id: '/lesson/$level'
      path: '/lesson/$level'
      fullPath: '/lesson/$level'
      preLoaderRoute: typeof LessonLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadenceRoute: CadenceRoute,
  CircleRoute: CircleRoute,
  CurriculumRoute: CurriculumRoute,
  DuelRoute: DuelRoute,
  HeatmapRoute: HeatmapRoute,
  IntervalRoute: IntervalRoute,
  OnboardingRoute: OnboardingRoute,
  PracticeRoute: PracticeRoute,
  RealtimeRoute: RealtimeRoute,
  RhythmRoute: RhythmRoute,
  ScaleRoute: ScaleRoute,
  SensoryRoute: SensoryRoute,
  SettingsRoute: SettingsRoute,
  TriadRoute: TriadRoute,
  LessonLevelRoute: LessonLevelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
